title: Missing Person Finder
description: 실종자 데이터를 Cloudflare Workers를 통해 수집 및 조회하는 프로젝트
theme: jekyll-theme-minimal

# Markdown 및 MathJax 설정
markdown: kramdown
kramdown:
  math_engine: mathjax
  input: GFM

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-readme-index

defaults:
  - scope:
      path: ""
    values:
      layout: "default"
      permalink: "/index.html"
